services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
      - ./backend/uploads:/app/uploads
      - ./frontend:/frontend
    environment:
      - PYTHONUNBUFFERED=1
